# Generated by Django 5.0.3 on 2024-03-25 10:28

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('espase client cloud', 'ESPASE CLIENT CLOUD'), ('vcloud director', 'VCLOUD DIRECTOR'), ('machine virtuelle', 'MACHINE VIRTUELLE'), ('stockage', 'STOCKAGE'), ('reseau', 'RESEAU'), ('recreation', 'RECREATION'), ('business', 'BUSINESS'), ('society', 'SOCIETY'), ('sports', 'SPORTS'), ('science', 'SCIENCE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=blogs.models.upload_to_path),
        ),
    ]
