global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api: # active l’API et le tableau de bord
  insecure: true
  dashboard: true

ping: {} # active le service de ping pour tester si Traefik est accessible.

providers:
  docker:
    endpoint: unix:///var/run/docker.sock  # permet à Traefik d’intégrer automatiquement les conteneurs Docker en lisant les informations via le socket Docker.
    exposedByDefault: false  # limite l’exposition aux seuls conteneurs explicitement configurés pour Traefik

entryPoints:
  web:
    address: :80 # définit un point d’entrée pour le trafic HTTP (port 80), qui peut servir de proxy pour les applications hébergées en local.